### ISSUE TITLE
yaml metadata will render a coleblock

### ISSUE THREAD

**Issue by ku-zhen** [LilaRest/obsidian-custom-classes#7] opened 2023-02-25 09:02 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/61906420/221348279-155b8f94-363a-451c-8fb9-fa41ea457799.png)

![image](https://user-images.githubusercontent.com/61906420/221348249-1446a296-c975-4fde-aa3a-74e5d133766b.png)

**To Reproduce**
1. when i open this plugin, the yaml metadata will render a code block
2. but i found some notes don't have this problem

**Comment by ku-zhen** [comment] 2023-02-25 10:07
![image](https://user-images.githubusercontent.com/61906420/221351256-929c32f1-1600-430f-a8d0-26ca672b1529.png)

**Comment by ku-zhen** [comment] 2023-02-25 10:08
I can use css to hide this code block, but there are still some errors in the console：

> ![image](https://user-images.githubusercontent.com/61906420/221351256-929c32f1-1600-430f-a8d0-26ca672b1529.png)

**Comment by LilaRest** [comment] 2023-02-25 10:09
@ku-zhen Hi, thanks for this report.
I'll investigate this one and #5 now, and will let you know.

**Comment by LilaRest** [comment] 2023-02-25 10:17
@ku-zhen I'm not able to reproduce this bug on the development vault. Can you send a the text content of a buggy Markdown note here ?

**Comment by ku-zhen** [comment] 2023-02-25 11:55
---
cssclass: cards,noyaml,fullwidth
banner: "zob_config/GIF/赛博朋克3.gif"
banner_y: 0.94309
---
###### <center>进行中</center>

```dataview
table without id ("![](" + cover + ")") as Cover, file.link as Name, author as Author,publisher,rating as Rating
from #book and !#社科
where contains(file.folder, "1 文献笔记收纳盒") and status="进行中"
sort rating desc
```


###### <center>搁置</center>

```dataview
table without id ("![](" + cover + ")") as Cover,  file.link as Name, author as Author,publisher,rating as Rating
from #book and !#社科
where contains(file.folder, "1 文献笔记收纳盒") and status="搁置"
sort rating desc
```


###### <center>待完成</center>

```dataview
table without id ("![](" + cover + ")") as Cover,  file.link as Name, author as Author,publisher,rating as Rating
from #book and !#社科
where contains(file.folder, "1 文献笔记收纳盒") and status="待完成"
sort rating desc
```


###### <center>已完成</center>

```dataview
table without id ("![](" + cover + ")") as Cover, file.link as Name, author as Author,publisher,rating as Rating
from #book and !#社科
where contains(file.folder, "1 文献笔记收纳盒") and status="已完成"
sort rating desc
```

**Comment by ku-zhen** [comment] 2023-02-25 11:56
@LilaRest you can try this .md note above

**Comment by LilaRest** [comment] 2023-02-25 12:02
> @LilaRest you can try this .md note above

There is no _Custom Classes_ block in the given example

**Comment by ku-zhen** [comment] 2023-02-25 12:28
> > @LilaRest you can try this .md note above
> 
> There is no _Custom Classes_ block in the given example

**yes, but every time I open this note, something happens, like this:**

> I can use css to hide this code block, but there are still some errors in the console：
> 
> > ![image](https://user-images.githubusercontent.com/61906420/221351256-929c32f1-1600-430f-a8d0-26ca672b1529.png)

**Comment by LilaRest** [comment] 2023-02-25 12:31
@ku-zhen Oh yes, those unwanted errors in the console will be fixed in the next release and are related to issue #5.

This issue is about the frontmatter that is displayed as a codeblock so I was requesting for an example of note that produces this bug.

**Comment by LilaRest** [comment] 2023-02-25 12:50
@ku-zhen That's ok I've been able to reproduce the bug.
A fixed version will be released today.

**Closed** 2023-02-25 13:23 UTC
Labels: bug
